# Generated by Django 5.1.1 on 2024-09-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("univ", "0003_alter_university_universityindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("country", models.CharField(max_length=100)),
                ("board", models.CharField(default="CBSE", max_length=100)),
                (
                    "degree",
                    models.CharField(
                        choices=[("UG", "Undergraduate"), ("PG", "Postgraduate")],
                        max_length=10,
                    ),
                ),
                ("course", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "course_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("score12", models.DecimalField(decimal_places=2, max_digits=5)),
                ("score10", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
