# Generated by Django 5.1.1 on 2024-09-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0005_alter_studentsdata_course_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdata',
            name='course_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdata',
            name='score10',
            field=models.DecimalField(decimal_places=1, default='0.0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentsdata',
            name='score12',
            field=models.DecimalField(decimal_places=1, default='0.0', max_digits=5),
        ),
    ]
