# Generated by Django 5.1.1 on 2024-09-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0008_alter_studentsdata_course_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdata',
            name='course',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
    ]
